version: '3'

services:

  monitoring-service:
    image: monitoring_img
    #    ports:
    #      - "8080:8080"
    environment:
      - DB_IP=host.docker.internal

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.person-ms.rule=PathPrefix(`/event`)"
      - "traefik.http.services.person-ms.loadbalancer.server.port=8082"

    networks:
      demo_net:
        aliases:
          - monitoring-service

networks:
  demo_net:
    external: true
