version: '3'

services:

  person-service:
    image: person_img
    #    ports:
    #      - "8080:8080"
    environment:
      - DB_IP=host.docker.internal

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.person-ms.rule=PathPrefix(/person)"
      - "traefik.http.services.person-ms.loadbalancer.server.port=8080"

    networks:
      demo_net:
        aliases:
          - person-service

networks:
  demo_net:
    external: true
